### PR TITLE
Fix `ListContents`, although it still fails

### PR DESCRIPTION
**Pull request by jedesah**
@wemrysi

### CODE REVIEW

**Comment by wemrysi** [comment]
What causes it to still fail?

**Comment by jedesah** [comment]
Since it only returns directories, the tests fail because in certain cases it expects a `FileName` instead of a `DirName`. In order for the test to pass we need to create a `FileName` for every `DirName` and then filter out the directories who don't contain directories themselves.

**Comment by wemrysi** [comment]
So this fixes returning relative dirs instead of absolute ones? If so then :+1:

**Comment by jedesah** [comment]
Ya, because `QueryFile` is doing `segAt(0, _)`, so now the results are wrong but close enough instead of being total bogus 😄

**Pull request merged**
